---
title: "explore_data_redo"
author: "Vince Protani"
date: "5/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidytext)
library(tidyr)
library(dplyr)
library(ggplot2)
library(plyr)
library(ggpubr)
```

```{r}
#setwd("C:/Users/vince/Desktop/natural_language_processor")
tidy.dir <- "../tidy_data/"
sources <- c("blogs", "news", "twitter")
num.sources <- length(sources)
tidy.source.files <- paste(tidy.dir, "en_US.", sources, ".source.txt", sep="")
tidy.tvt.files <- paste(tidy.dir, "en_US.", sources, "tvt.txt", sep="")
index <- 1:num.sources
```

```{r}
source.data <- lapply(tidy.source.files, read.table, header=TRUE, sep="\t", fill=TRUE, quote="", stringsAsFactors=FALSE)
source.data <- lapply(index, function(x) mutate(source.data[[x]], source=sources[x]))
source.data <- source.data %>% bind_rows() %>% as_tibble()
```

```{r}
is_word <- function(x) { grepl("^[A-Za-z]+$", x) }
vowel_repeats <- function(x) { grepl("(a|i|u){2,}|(e|o){3,}", x) }
```

```{r}
bigrams <- source.data %>% unnest_tokens(output=ngram, input=sentence, token="ngrams", n=2) 
bigrams <- bigrams %>% separate(col=ngram, into=c("word1", "word2"), sep=" +")
bigrams <- bigrams %>% filter(is_word(word1) & is_word(word2)) %>% filter(!(vowel_repeats(word1) | vowel_repeats(word2))) %>% filter(word1!=word2)
bigrams <- bigrams %>% group_by(source, word1)
bigrams <- bigrams %>% count(word2)
bigrams <- bigrams %>% arrange(source, desc(n), word1, word2)
```

```{r}
top.by.source <- bigrams %>% ungroup() %>% ddply(.(source), function(x) x[1:10,]) %>% mutate(combined=paste(word1, word2)) %>% as_tibble()
top.all <- bigrams %>% ungroup() %>% select(-source) %>% group_by(word1, word2) %>% dplyr::summarize(n=sum(n)) %>% arrange(desc(n)) %>% (function(x) x[1:10,]) %>% mutate(combined=paste(word1, word2))

p1 <- ggplot(top.by.source, aes(x=combined, y=n, fill=n)) + geom_bar(stat="identity") + facet_wrap(source~.) + coord_flip() + labs(x="", y="") + theme(legend.position="none")
p2 <- ggplot(top.all, aes(x=combined, y=n, fill=n)) + geom_bar(stat="identity") + coord_flip() + labs(x="", y="") + theme(legend.position="none")
ggarrange(p1, p2, nrow=2, ncol=1) %>% annotate_figure(top="bigram frequency")
```

```{r}
end.words2 <- bigrams %>% ungroup() %>% group_by(word2) %>% select(word2, n) %>% summarize(count=sum(n)) %>% mutate(freq=count/sum(count))
freq.end.stop <- end.words2 %>% filter(word2 %in% stop_words$word) %>% summarize(total=sum(freq))
freq.end.norm <- 1 - freq.end.stop
```
