---
title: "new_explorer"
author: "Vince Protani"
date: "6/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(ggpubr)
n <- 1:4
sources <- c("blogs", "news", "twitter")
```

```{r}
sep.plots <- list()
tot.plots <- list()
for (II in n) {
  ngram.files <- paste0("../tidy_data/en_US.", sources, ".", II, "grams.txt")
	ngram.str <- paste0(II, "gram")
	
	ngrams <- lapply(ngram.files, fread, sep=",")
  ngrams <- Reduce("rbind", ngrams)
	
	if (II > 1) {
	  ngrams$ngram <- paste(ngrams$start, ngrams$end, sep="_")
	}
  else {
    ngrams$ngram <- ngrams$start
  }
  ngrams$start <- NULL
	top <- ngrams[,head(.SD, 10), by=source]
	sep.plots[[II]] <- ggplot(top, aes(x=ngram, y=count, fill=count)) + geom_bar(stat="identity") + facet_wrap(source~., nrow=3) + coord_flip() + theme(legend.position="none") + labs(x=ngram.str, y="count")

	ngrams$source <- NULL
	if (II > 1) { ngrams$end <- NULL }
	ngrams <- ngrams[,.(count=sum(count)), by=ngram]
	setorder(ngrams, -count, ngram)
	ngrams <- ngrams[1:20,]

	tot.plots[[II]] <- ggplot(ngrams, aes(x=ngram, y=count, fill=count)) + geom_bar(stat="identity") + coord_flip() + theme(legend.position="none") + labs(x=ngram.str, y="count", title="all sources")
}
```

## Unigram Analysis

```{r}
ggarrange(sep.plots[[1]], tot.plots[[1]], ncol=2)
```

## Bigram Analysis

```{r}
ggarrange(sep.plots[[2]], tot.plots[[2]], ncol=2)
```

## Trigram Analysis

```{r}
ggarrange(sep.plots[[3]], tot.plots[[3]], ncol=2)
```

## Quadrigram Analysis

```{r}
ggarrange(sep.plots[[4]], tot.plots[[4]], ncol=2)
```

